posgradolineas:
    pattern:  /posgradmin/posgradolineas
    defaults: { _controller: PosgradoLineasBundle:PosgradoLineas:index }

_posgradolineas:
    pattern: /posgradmin/posgradolineas/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: posgradolineas}

posgradolineas_new:
    pattern:  /posgradmin/posgradolineas/new
    defaults: { _controller: PosgradoLineasBundle:PosgradoLineas:new }

posgradolineas_edit:
    pattern:  /posgradmin/posgradolineas/edit/{id}
    defaults: { _controller: PosgradoLineasBundle:PosgradoLineas:edit }

posgradolineas_create:
    pattern:  /posgradmin/posgradolineas/create
    defaults: { _controller: PosgradoLineasBundle:PosgradoLineas:create }

posgradolineas_update:
    pattern:  /posgradmin/posgradolineas/update/{id}
    defaults: { _controller: PosgradoLineasBundle:PosgradoLineas:update }

posgradolineas_delete:
    pattern:  /posgradmin/posgradolineas/delete/{id}
    defaults: { _controller: PosgradoLineasBundle:PosgradoLineas:delete }
