alumnosproyectos:
    pattern:  /posgradmin/alumnosproyectos
    defaults: { _controller: AlumnosProyectosBundle:AlumnosProyectos:index }

_alumnosproyectos:
    pattern: /posgradmin/alumnosproyectos/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: alumnosproyectos}

alumnosproyectos_new:
    pattern:  /posgradmin/alumnosproyectos/new
    defaults: { _controller: AlumnosProyectosBundle:AlumnosProyectos:new }

alumnosproyectos_edit:
    pattern:  /posgradmin/alumnosproyectos/edit/{id}
    defaults: { _controller: AlumnosProyectosBundle:AlumnosProyectos:edit }

alumnosproyectos_create:
    pattern:  /posgradmin/alumnosproyectos/create
    defaults: { _controller: AlumnosProyectosBundle:AlumnosProyectos:create }

alumnosproyectos_update:
    pattern:  /posgradmin/alumnosproyectos/update/{id}
    defaults: { _controller: AlumnosProyectosBundle:AlumnosProyectos:update }

alumnosproyectos_delete:
    pattern:  /posgradmin/alumnosproyectos/delete/{id}
    defaults: { _controller: AlumnosProyectosBundle:AlumnosProyectos:delete }
