areas:
    pattern:  /posgradmin/areas
    defaults: { _controller: AreasBundle:Areas:index }

_areas:
    pattern: /posgradmin/areas/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: areas}

areas_new:
    pattern:  /posgradmin/areas/new
    defaults: { _controller: AreasBundle:Areas:new }

areas_edit:
    pattern:  /posgradmin/areas/edit/{id}
    defaults: { _controller: AreasBundle:Areas:edit }

areas_update:
    pattern:  /posgradmin/areas/update/{id}
    defaults: { _controller: AreasBundle:Areas:update }

areas_delete:
    pattern:  /posgradmin/areas/delete/{id}
    defaults: { _controller: AreasBundle:Areas:delete }

areas_public:
    pattern:  /areas
    defaults: { _controller: AreasBundle:AreasPublic:index }