posgrado_investigadores:
    resource: "@PosgradoInvestigadoresBundle/Resources/config/routing.yml"
    prefix:   /

posgrado_lineas:
    resource: "@PosgradoLineasBundle/Resources/config/routing.yml"
    prefix:   /

posgrado_areas:
    resource: "@PosgradoAreasBundle/Resources/config/routing.yml"
    prefix:   /

posgrado_alumnos:
    resource: "@PosgradoAlumnosBundle/Resources/config/routing.yml"
    prefix:   /

posgrados:
    resource: "@PosgradosBundle/Resources/config/routing.yml"
    prefix:   /

noticias:
    resource: "@NoticiasBundle/Resources/config/routing.yml"
    prefix:   /

back_end:
    resource: "@BackEndBundle/Resources/config/routing.yml"
    prefix:   /

proyectos_productos:
    resource: "@ProyectosProductosBundle/Resources/config/routing.yml"
    prefix:   /

productos_academicos:
    resource: "@ProductosAcademicosBundle/Resources/config/routing.yml"
    prefix:   /

areas_proyectos:
    resource: "@AreasProyectosBundle/Resources/config/routing.yml"
    prefix:   /

areas:
    resource: "@AreasBundle/Resources/config/routing.yml"
    prefix:   /

investigadores_lineas:
    resource: "@InvestigadoresLineasBundle/Resources/config/routing.yml"
    prefix:   /

alumnos_proyectos:
    resource: "@AlumnosProyectosBundle/Resources/config/routing.yml"

investigador_proyecto:
    resource: "@InvestigadorProyectoBundle/Resources/config/routing.yml"
    prefix:   /

lineas_investigacion:
    resource: "@LineasInvestigacionBundle/Resources/config/routing.yml"
    prefix:   /

proyectos:
    resource: "@ProyectosBundle/Resources/config/routing.yml"
    prefix:   /

alumnos:
    resource: "@AlumnosBundle/Resources/config/routing.yml"
    prefix:   /

investigadores:
    resource: "@InvestigadoresBundle/Resources/config/routing.yml"
    prefix:   /

portada:
    resource: "@PortadaBundle/Resources/config/routing.yml"
    prefix:   /