lineas:
    pattern:  /posgradmin/lineas
    defaults: { _controller: LineasInvestigacionBundle:LineasInvestigacion:index }

_lineas:
    pattern: /posgradmin/lineas/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: lineas}

lineas_new:
    pattern:  /posgradmin/lineas/new
    defaults: { _controller: LineasInvestigacionBundle:LineasInvestigacion:new }

lineas_edit:
    pattern:  /posgradmin/lineas/edit/{id}
    defaults: { _controller: LineasInvestigacionBundle:LineasInvestigacion:edit }

lineas_create:
    pattern:  /posgradmin/lineas/create
    defaults: { _controller: LineasInvestigacionBundle:LineasInvestigacion:create }

lineas_update:
    pattern:  /posgradmin/lineas/update/{id}
    defaults: { _controller: LineasInvestigacionBundle:LineasInvestigacion:update }

lineas_delete:
    pattern:  /posgradmin/lineas/delete/{id}
    defaults: { _controller: LineasInvestigacionBundle:LineasInvestigacion:delete }

lineas_public:
    pattern:  /lineas
    defaults: { _controller: LineasInvestigacionBundle:LineasInvestigacionPublic:index }